package uoa.nightingales.aiservicenode.services;

import java.util.List;

public interface ChatGptYoutubeRecommendService {
    /**
     * Get the relevant 10 categories
     * @param userInput Get from the frontend that what user want to see
     * @return return the most relevant 10 categories from generated by chatgpt
     */
    List<String> getUserInputRelevantCategory(String userInput);

    /**
     * Get the not relevant 10 categories
     * @param userInput Get from the frontend that what user want to see
     * @return return the most relevant 10 categories from generated by chatgpt
     */
    List<String> getUserInputNotRelevantCategory(String userInput);

    /**
     * Get the youtube video category
     * @param youtubeDesc
     * @return
     */
    List<String> getYoutubeRelevantCategory(String youtubeDesc);
}
