spring:
  application:
    name: SpotifyServiceNode


spotify:
  client:
    id: ${SPOTIFY_CLIENT_ID}
    secret: ${SPOTIFY_CLIENT_SECRET}

  baseUrl: https://api.spotify.com/v1
  redirect:
    uri: http://localhost:30051/api/auth/callback


cache:
  primary: primary_cache
  secondary: secondary_cache

server:
  port: 30051
