spring:
  application:
    name: MongoDBServiceNode
  data:
    mongodb:
      uri: ${MONGODB_URL}

  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=100,maximumSize=500,expireAfterAccess=1800s

server:
  port: 30053