package uoa.nightingales.mongodbservicenode.enums;

public enum Genre {

    // News and Information
    NEWS,
    EDUCATION,
    SCIENCE,
    TECHNOLOGY,
    HEALTH,
    ENVIRONMENT,
    POLITICS,
    SOCIETY,
    HISTORY,
    LAW,

    // Entertainment
    MUSIC,
    COMEDY,
    MOVIES,
    ANIMATION,
    DOCUMENTARY,
    DRAMA,
    FANTASY,
    HORROR,
    ROMANCE,
    ACTION,
    ADVENTURE,
    THRILLER,
    MYSTERY,
    SCI_FI,
    MUSICAL,
    DANCE,
    MAGIC,
    REALITY,

    // Lifestyle and Hobbies
    COOKING,
    TRAVEL,
    FASHION,
    BEAUTY,
    LIFESTYLE,
    DIY,
    CRAFTS,
    ART,
    PHOTOGRAPHY,
    GARDENING,
    PET_CARE,
    INTERIOR_DESIGN,
    VLOGS,

    // Sports and Fitness
    SPORTS,
    FITNESS,
    BODYBUILDING,
    YOGA,
    MEDITATION,
    RUNNING,
    CYCLING,
    SWIMMING,
    MARTIAL_ARTS,
    TEAM_SPORTS,
    EXTREME_SPORTS,
    OUTDOOR_RECREATION,

    // Gaming and Technology
    GAMING,
    VIDEO_GAMES,
    BOARD_GAMES,
    CARD_GAMES,
    PUZZLE_GAMES,
    ROLE_PLAYING,
    SIMULATION,
    STRATEGY,
    SPORTS_GAMES,
    MMO,
    MOBA,
    BATTLE_ROYALE,
    VIRTUAL_REALITY,
    AUGMENTED_REALITY,
    SOFTWARE_DEVELOPMENT,
    CYBER_SECURITY,
    ROBOTICS,
    AI,

    // Education and Learning
    TUTORIALS,
    LANGUAGE_LEARNING,
    ONLINE_COURSES,
    WORKSHOPS,
    WEBINARS,
    PODCASTS,
    LITERATURE,
    PHILOSOPHY,
    PSYCHOLOGY,
    MATHEMATICS,
    ENGINEERING,
    MEDICINE,

    // Culture and Community
    CULTURE,
    RELIGION,
    CHARITY,
    VOLUNTEERING,
    LOCAL_EVENTS,
    FESTIVALS,
    CONFERENCES,
    EXHIBITIONS,
    FAIRS,

    // Business and Finance
    BUSINESS,
    FINANCE,
    MARKETING,
    ENTREPRENEURSHIP,
    INVESTING,
    STOCK_MARKET,
    REAL_ESTATE,

    // Miscellaneous
    REVIEWS,
    UNBOXING,
    INTERVIEWS,
    TALK_SHOWS,
    COMPETITIONS,
    AWARDS,
    STREAMING,
}